# Generated by Django 4.1.5 on 2023-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("publishing_timestamp", models.DateTimeField(auto_now_add=True)),
                ("thumbnail_urls", models.CharField(max_length=150)),
            ],
        ),
    ]
