# Generated by Django 4.1.5 on 2023-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_crawl_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="added_to_db",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="publishing_timestamp",
            field=models.DateTimeField(),
        ),
    ]
