# Generated by Django 4.1.5 on 2023-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "youtube_crawl_api",
            "0002_video_added_to_db_alter_video_publishing_timestamp",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="channel_title",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
