# Generated by Django 4.1.5 on 2023-01-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_crawl_api", "0003_video_channel_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="yt_video_id",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
