# Generated by Django 4.1.5 on 2023-01-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_crawl_api", "0004_video_yt_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail_urls",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="yt_video_id",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
